### ISSUE TITLE
Want to add GUI support for random mouse click event script

### ISSUE THREAD

**Issue by iamSRQansari** [aiwithab/Scripts#3]
in random mouse click script mouse pointer location coordinates are selected randomly using random integer, I think it will be cool if user selects the area in which the mouse should be clicked by dragging the mouse. hope it will ease the process. Thankyou!

**Comment by aiwithab** [comment]
Cool, lets see if we can do that. What do you think how is should be?

**Comment by aiwithab** [comment]
I made a simple GUI hope you'll like it it needed to be integrated to script.

**Comment by aiwithab** [comment]
I did it brother kindly check it out if not working properly create issue
accordingly , thanks keep contributing. Happy hacking
